# Most of the configuration items below are ignored when remote management is enabled.
# Please refer to the following document for details:
# https://rasp.baidu.com/doc/setup/others.html#java-standalone
 
# <general settings>
# 
# plugin.timeout.millis: 100
# body.maxbytes: 4096
# plugin.filter: true
# plugin.maxstack: 100
# ognl.expression.minlength: 30
# clientip.header: ClientIP
# lru.max_size: 100
# inject.urlprefix:
# log.maxburst: 100
# log.maxbackup: 30
# decompile.enable: false
# block.status_code: 302
# request.param_encoding:
hooks.ignore: http_output
# debug.level: 0
#hook.white:
#  "localhost:8080/vulns/011-ssrf-commons-httpclient.jsp":
#    - "sql"
#    - "ssrf"
#  "www.test.com/test2":
#    - "sql"
#    - "ssrf"
#inject.custom_headers:
#   X-Content-Type-Options: nosniff
#   X-Frame-Options: deny
#   X-XSS-Protection: 1; mode=block
#   X-Download-Options: noopen

# <response to malicious requests>
# 
# block.redirect_url: "https://rasp.baidu.com/blocked/?request_id=%request_id%"
# block.content_json: "{\"error\":true, \"reason\": \"Request blocked by OpenRASP\", \"request_id\": \"%request_id%\"}"
# block.content_xml: "<?xml version=\"1.0\"?><doc><error>true</error><reason>Request blocked by OpenRASP</reason><request_id>%request_id%</request_id></doc>"
# block.content_html: "</script><script>location.href=\"https://rasp.baidu.com/blocked2/?request_id=%request_id%\"</script>"

# <remote management>
#
cloud.enable: true
cloud.backend_url: http://rasp-cloud:8086
cloud.app_id: 192d1cb737394b74b640dc9de66fc7b0b49e1423
cloud.app_secret: HUL1Z0zy1BuSFOWI2lHWqzzZ2Yrq12DJDeyHFDxcEAk 
cloud.heartbeat_interval: 10

# <syslog configuration>
#
# syslog.enable: false
# syslog.url:
# syslog.tag: OpenRASP
# syslog.reconnect_interval: 300000
# syslog.facility: 1


